--Create impact table

Create TABLE #Impact(Codename NVARCHAR(100),Impact NVARCHAR(5));
GO

INSERT INTO #Impact(Codename,Impact)
VALUES
			('Apollo Lake','Low'),
			('Arrandale','High'),
			('Bay Trail','High'),
			('Bloomfield','High'),
			('Broadwell','High'),
			('Cherry Trail','High'),
			('Clarkdale','High'),
			('Coffee Lake','Low'),
			('Crystal Well','High'),
			('Dempsey','High'),
			('Devils Canyon','High'),
			('Gemini Lake','Low'),
			('Harpertown','High'),
			('Haswell','High'),
			('Ivy Bridge','High'),
			('Ivy Bridge EN','High'),
			('Ivy Bridge EP','High'),
			('Kaby Lake','Low'),
			('Nehalem EP','High'),
			('Nehalem EX','High'),
			('Sandy Bridge','High'),
			('Sandy Bridge EN','High'),
			('Sandy Bridge EP','High'),
			('Skylake','Low'),
			('Westmere','High'),
			('Westmere EX','High'),
			('Wolfdale','High'),
			('Woodcrest','High');
GO

--Create processor codename reference table

CREATE TABLE #Processors(ProcName NVARCHAR(300), Codename NVARCHAR(100));
GO
INSERT INTO #Processors (ProcName,CodeName)
VALUES 		('Intel(R) Core(TM) i7-5950HQ','Broadwell'),
			('Intel(R) Core(TM) i7-5850HQ','Broadwell'),
			('Intel(R) Core(TM) i7-5850EQ','Broadwell'),
			('Intel(R) Core(TM) i7-5750HQ','Broadwell'),
			('Intel(R) Core(TM) i7-5700EQ','Broadwell'),
			('Intel(R) Core(TM) i7-5700HQ','Broadwell'),
			('Intel(R) Core(TM) i7-5775R','Broadwell'),
			('Intel(R) Core(TM) i7-5775C','Broadwell'),
			('Intel(R) Core(TM) i7-5650U','Broadwell'),
			('Intel(R) Core(TM) i7-5600U','Broadwell'),
			('Intel(R) Core(TM) i7-5557U','Broadwell'),
			('Intel(R) Core(TM) i7-5550U','Broadwell'),
			('Intel(R) Core(TM) i7-5500U','Broadwell'),
			('Intel(R) Core(TM) i5-5675R','Broadwell'),
			('Intel(R) Core(TM) i5-5675C','Broadwell'),
			('Intel(R) Core(TM) i5-5575R','Broadwell'),
			('Intel(R) Core(TM) i5-5350U','Broadwell'),
			('Intel(R) Core(TM) i5-5350H','Broadwell'),
			('Intel(R) Core(TM) i5-5300U','Broadwell'),
			('Intel(R) Core(TM) i5-5287U','Broadwell'),
			('Intel(R) Core(TM) i5-5257U','Broadwell'),
			('Intel(R) Core(TM) i5-5250U','Broadwell'),
			('Intel(R) Core(TM) i5-5200U','Broadwell'),
			('Intel(R) Core(TM) i3-5157U','Broadwell'),
			('Intel(R) Core(TM) i3-5020U','Broadwell'),
			('Intel(R) Core(TM) i3-5015U','Broadwell'),
			('Intel(R) Core(TM) i3-5010U','Broadwell'),
			('Intel(R) Core(TM) i3-5005U','Broadwell'),
			('Intel(R) Core(TM) M-5Y71','Broadwell'),
			('Intel(R) Core(TM) M-5Y70','Broadwell'),
			('Intel(R) Core(TM) M-5Y51','Broadwell'),
			('Intel(R) Core(TM) M-5Y31','Broadwell'),
			('Intel(R) Core(TM) M-5Y10c','Broadwell'),
			('Intel(R) Core(TM) M-5Y10a','Broadwell'),
			('Intel(R) Core(TM) M-5Y10','Broadwell'),
			('Intel(R) Pentium(R) D1519','Broadwell'),
			('Intel(R) Pentium(R) D1517','Broadwell'),
			('Intel(R) Pentium(R) D1509','Broadwell'),
			('Intel(R) Pentium(R) D1508','Broadwell'),
			('Intel(R) Pentium(R) D1507','Broadwell'),
			('Intel(R) Pentium(R) 3805U','Broadwell'),
			('Intel(R) Pentium(R) 3825U','Broadwell'),
			('Intel(R) Celeron(R) 3765U','Broadwell'),
			('Intel(R) Celeron(R) 3755U','Broadwell'),
			('Intel(R) Celeron(R) 3215U','Broadwell'),
			('Intel(R) Celeron(R) 3205U','Broadwell'),
			('Intel(R) Xeon(R) E7-8894 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-8893 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-8891 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-8890 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-8880 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-8870 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-8867 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-8860 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-4850 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-4830 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-4820 v4','Broadwell'),
			('Intel(R) Xeon(R) E7-4809 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-4669 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-4667 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-4660 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-4655 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-4650 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-4640 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-4628L v4','Broadwell'),
			('Intel(R) Xeon(R) E5-4627 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-4620 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-4610 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2699A v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2699R v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2699 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2698 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2697 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2697A v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2695 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2690 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2687W v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2683 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2680 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2667 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2660 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2658 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2650 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2650L v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2648L v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2643 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2640 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2637 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2630 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2630L v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2628L v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2623 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2620 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2618L v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2609 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2608L v4','Broadwell'),
			('Intel(R) Xeon(R) E5-2603 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-1680 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-1660 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-1650 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-1630 v4','Broadwell'),
			('Intel(R) Xeon(R) E5-1620 v4','Broadwell'),
			('Intel(R) Xeon(R) E3-1285L v4','Broadwell'),
			('Intel(R) Xeon(R) E3-1285 v4','Broadwell'),
			('Intel(R) Xeon(R) E3-1278L v4','Broadwell'),
			('Intel(R) Xeon(R) E3-1265L v4','Broadwell'),
			('Intel(R) Xeon(R) E3-1258L v4','Broadwell'),
			('Intel(R) Xeon(R) D-1577','Broadwell'),
			('Intel(R) Xeon(R) D-1571','Broadwell'),
			('Intel(R) Xeon(R) D-1567','Broadwell'),
			('Intel(R) Xeon(R) D-1559','Broadwell'),
			('Intel(R) Xeon(R) D-1557','Broadwell'),
			('Intel(R) Xeon(R) D-1553N','Broadwell'),
			('Intel(R) Xeon(R) D-1548','Broadwell'),
			('Intel(R) Xeon(R) D-1543N','Broadwell'),
			('Intel(R) Xeon(R) D-1541','Broadwell'),
			('Intel(R) Xeon(R) D-1540','Broadwell'),
			('Intel(R) Xeon(R) D-1539','Broadwell'),
			('Intel(R) Xeon(R) D-1537','Broadwell'),
			('Intel(R) Xeon(R) D-1533N','Broadwell'),
			('Intel(R) Xeon(R) D-1531','Broadwell'),
			('Intel(R) Xeon(R) D-1529','Broadwell'),
			('Intel(R) Xeon(R) D-1528','Broadwell'),
			('Intel(R) Xeon(R) D-1527','Broadwell'),
			('Intel(R) Xeon(R) D-1523N','Broadwell'),
			('Intel(R) Xeon(R) D-1521','Broadwell'),
			('Intel(R) Xeon(R) D-1520','Broadwell'),
			('Intel(R) Xeon(R) D-1518','Broadwell'),
			('Intel(R) Xeon(R) D-1513N','Broadwell'),
			('Intel(R) Core(TM) i9-7980XE Extreme Edition','Skylake'),
			('Intel(R) Core(TM) i9-7960X X-series','Skylake'),
			('Intel(R) Core(TM) i9-7940X X-series','Skylake'),
			('Intel(R) Core(TM) i9-7920X X-series','Skylake'),
			('Intel(R) Core(TM) i9-7900X X-series','Skylake'),
			('Intel(R) Core(TM) i7-7820X X-series','Skylake'),
			('Intel(R) Core(TM) i7-7800X X-series','Skylake'),
			('Intel(R) Core(TM) i7-6970HQ','Skylake'),
			('Intel(R) Core(TM) i7-6920HQ','Skylake'),
			('Intel(R) Core(TM) i7-6870HQ','Skylake'),
			('Intel(R) Core(TM) i7-6822EQ','Skylake'),
			('Intel(R) Core(TM) i7-6820HQ','Skylake'),
			('Intel(R) Core(TM) i7-6820HK','Skylake'),
			('Intel(R) Core(TM) i7-6820EQ','Skylake'),
			('Intel(R) Core(TM) i7-6785R','Skylake'),
			('Intel(R) Core(TM) i7-6700K','Skylake'),
			('Intel(R) Core(TM) i7-6700T','Skylake'),
			('Intel(R) Core(TM) i7-6700TE','Skylake'),
			('Intel(R) Core(TM) i7-6700','Skylake'),
			('Intel(R) Core(TM) i7-6770HQ','Skylake'),
			('Intel(R) Core(TM) i7-6700HQ','Skylake'),
			('Intel(R) Core(TM) i7-6660U','Skylake'),
			('Intel(R) Core(TM) i7-6650U','Skylake'),
			('Intel(R) Core(TM) i7-6600U','Skylake'),
			('Intel(R) Core(TM) i7-6567U','Skylake'),
			('Intel(R) Core(TM) i7-6560U','Skylake'),
			('Intel(R) Core(TM) i7-6500U','Skylake'),
			('Intel(R) Core(TM) i5-6600','Skylake'),
			('Intel(R) Core(TM) i5-6685R','Skylake'),
			('Intel(R) Core(TM) i5-6600K','Skylake'),
			('Intel(R) Core(TM) i5-6600T','Skylake'),
			('Intel(R) Core(TM) i5-6585R','Skylake'),
			('Intel(R) Core(TM) i5-6500','Skylake'),
			('Intel(R) Core(TM) i5-6500T','Skylake'),
			('Intel(R) Core(TM) i5-6500TE','Skylake'),
			('Intel(R) Core(TM) i5-6402P','Skylake'),
			('Intel(R) Core(TM) i5-6400','Skylake'),
			('Intel(R) Core(TM) i5-6400T','Skylake'),
			('Intel(R) Core(TM) i5-6440EQ','Skylake'),
			('Intel(R) Core(TM) i5-6440HQ','Skylake'),
			('Intel(R) Core(TM) i5-6442EQ','Skylake'),
			('Intel(R) Core(TM) i5-6360U','Skylake'),
			('Intel(R) Core(TM) i5-6350HQ','Skylake'),
			('Intel(R) Core(TM) i5-6300HQ','Skylake'),
			('Intel(R) Core(TM) i5-6300U','Skylake'),
			('Intel(R) Core(TM) i5-6200U','Skylake'),
			('Intel(R) Core(TM) i5-6260U','Skylake'),
			('Intel(R) Core(TM) i5-6267U','Skylake'),
			('Intel(R) Core(TM) i5-6287U','Skylake'),
			('Intel(R) Core(TM) i3-6300','Skylake'),
			('Intel(R) Core(TM) i3-6300T','Skylake'),
			('Intel(R) Core(TM) i3-6320','Skylake'),
			('Intel(R) Core(TM) i3-6100E','Skylake'),
			('Intel(R) Core(TM) i3-6100H','Skylake'),
			('Intel(R) Core(TM) i3-6100U','Skylake'),
			('Intel(R) Core(TM) i3-6102E','Skylake'),
			('Intel(R) Core(TM) i3-6157U','Skylake'),
			('Intel(R) Core(TM) i3-6167U','Skylake'),
			('Intel(R) Core(TM) i3-6100','Skylake'),
			('Intel(R) Core(TM) i3-6100T','Skylake'),
			('Intel(R) Core(TM) i3-6100TE','Skylake'),
			('Intel(R) Core(TM) i3-6006U','Skylake'),
			('Intel(R) Core(TM) i3-6098P','Skylake'),
			('Intel(R) Core(TM) m7-6Y75','Skylake'),
			('Intel(R) Core(TM) m5-6Y57','Skylake'),
			('Intel(R) Core(TM) m5-6Y54','Skylake'),
			('Intel(R) Core(TM) m3-6Y30','Skylake'),
			('Intel(R) Pentium(R) G4520','Skylake'),
			('Intel(R) Pentium(R) G4500T','Skylake'),
			('Intel(R) Pentium(R) G4500','Skylake'),
			('Intel(R) Pentium(R) G4400TE','Skylake'),
			('Intel(R) Pentium(R) G4400T','Skylake'),
			('Intel(R) Pentium(R) G4400','Skylake'),
			('Intel(R) Pentium(R) 4405Y','Skylake'),
			('Intel(R) Pentium(R) 4405U','Skylake'),
			('Intel(R) Celeron(R) G3920','Skylake'),
			('Intel(R) Celeron(R) G3902E','Skylake'),
			('Intel(R) Celeron(R) G3900TE','Skylake'),
			('Intel(R) Celeron(R) G3900E','Skylake'),
			('Intel(R) Celeron(R) G3900T','Skylake'),
			('Intel(R) Celeron(R) G3900','Skylake'),
			('Intel(R) Celeron(R) 3955U','Skylake'),
			('Intel(R) Celeron(R) 3855U','Skylake'),
			('Intel(R) Xeon(R) Platinum 8180M','Skylake'),
			('Intel(R) Xeon(R) Platinum 8180','Skylake'),
			('Intel(R) Xeon(R) Platinum 8176M','Skylake'),
			('Intel(R) Xeon(R) Platinum 8176F','Skylake'),
			('Intel(R) Xeon(R) Platinum 8176','Skylake'),
			('Intel(R) Xeon(R) Platinum 8170M','Skylake'),
			('Intel(R) Xeon(R) Platinum 8170','Skylake'),
			('Intel(R) Xeon(R) Platinum 8168','Skylake'),
			('Intel(R) Xeon(R) Platinum 8164','Skylake'),
			('Intel(R) Xeon(R) Platinum 8160T','Skylake'),
			('Intel(R) Xeon(R) Platinum 8160M','Skylake'),
			('Intel(R) Xeon(R) Platinum 8160F','Skylake'),
			('Intel(R) Xeon(R) Platinum 8160','Skylake'),
			('Intel(R) Xeon(R) Platinum 8158','Skylake'),
			('Intel(R) Xeon(R) Platinum 8156','Skylake'),
			('Intel(R) Xeon(R) Platinum 8153','Skylake'),
			('Intel(R) Xeon(R) Gold 6154','Skylake'),
			('Intel(R) Xeon(R) Gold 6152','Skylake'),
			('Intel(R) Xeon(R) Gold 6150','Skylake'),
			('Intel(R) Xeon(R) Gold 6148F','Skylake'),
			('Intel(R) Xeon(R) Gold 6148','Skylake'),
			('Intel(R) Xeon(R) Gold 6146','Skylake'),
			('Intel(R) Xeon(R) Gold 6144','Skylake'),
			('Intel(R) Xeon(R) Gold 6142M','Skylake'),
			('Intel(R) Xeon(R) Gold 6142F','Skylake'),
			('Intel(R) Xeon(R) Gold 6142','Skylake'),
			('Intel(R) Xeon(R) Gold 6140M','Skylake'),
			('Intel(R) Xeon(R) Gold 6140','Skylake'),
			('Intel(R) Xeon(R) Gold 6138T','Skylake'),
			('Intel(R) Xeon(R) Gold 6138F','Skylake'),
			('Intel(R) Xeon(R) Gold 6138','Skylake'),
			('Intel(R) Xeon(R) Gold 6136','Skylake'),
			('Intel(R) Xeon(R) Gold 6134M','Skylake'),
			('Intel(R) Xeon(R) Gold 6134','Skylake'),
			('Intel(R) Xeon(R) Gold 6132','Skylake'),
			('Intel(R) Xeon(R) Gold 6130T','Skylake'),
			('Intel(R) Xeon(R) Gold 6130F','Skylake'),
			('Intel(R) Xeon(R) Gold 6130','Skylake'),
			('Intel(R) Xeon(R) Gold 6128','Skylake'),
			('Intel(R) Xeon(R) Gold 6126T','Skylake'),
			('Intel(R) Xeon(R) Gold 6126F','Skylake'),
			('Intel(R) Xeon(R) Gold 6126','Skylake'),
			('Intel(R) Xeon(R) Gold 5122','Skylake'),
			('Intel(R) Xeon(R) Gold 5120T','Skylake'),
			('Intel(R) Xeon(R) Gold 5120','Skylake'),
			('Intel(R) Xeon(R) Gold 5119T','Skylake'),
			('Intel(R) Xeon(R) Gold 5118','Skylake'),
			('Intel(R) Xeon(R) Gold 5115','Skylake'),
			('Intel(R) Xeon(R) Silver 4116T','Skylake'),
			('Intel(R) Xeon(R) Silver 4116','Skylake'),
			('Intel(R) Xeon(R) Silver 4114T','Skylake'),
			('Intel(R) Xeon(R) Silver 4114','Skylake'),
			('Intel(R) Xeon(R) Silver 4112','Skylake'),
			('Intel(R) Xeon(R) Silver 4110','Skylake'),
			('Intel(R) Xeon(R) Silver 4109T','Skylake'),
			('Intel(R) Xeon(R) Silver 4108','Skylake'),
			('Intel(R) Xeon(R) Bronze 3106','Skylake'),
			('Intel(R) Xeon(R) Bronze 3104','Skylake'),
			('Intel(R) Xeon(R) E3-1585 v5','Skylake'),
			('Intel(R) Xeon(R) E3-1585L v5','Skylake'),
			('Intel(R) Xeon(R) E3-1578L v5','Skylake'),
			('Intel(R) Xeon(R) E3-1575M v5','Skylake'),
			('Intel(R) Xeon(R) E3-1565L v5','Skylake'),
			('Intel(R) Xeon(R) E3-1558L v5','Skylake'),
			('Intel(R) Xeon(R) E3-1545M v5','Skylake'),
			('Intel(R) Xeon(R) E3-1535M v5','Skylake'),
			('Intel(R) Xeon(R) E3-1515M v5','Skylake'),
			('Intel(R) Xeon(R) E3-1505M v5','Skylake'),
			('Intel(R) Xeon(R) E3-1505L v5','Skylake'),
			('Intel(R) Xeon(R) E3-1280 v5','Skylake'),
			('Intel(R) Xeon(R) E3-1275 v5','Skylake'),
			('Intel(R) Xeon(R) E3-1270 v5','Skylake'),
			('Intel(R) Xeon(R) E3-1268L v5','Skylake'),
			('Intel(R) Xeon(R) E3-1260L v5','Skylake'),
			('Intel(R) Xeon(R) E3-1245 v5','Skylake'),
			('Intel(R) Xeon(R) E3-1240L v5','Skylake'),
			('Intel(R) Xeon(R) E3-1240 v5','Skylake'),
			('Intel(R) Xeon(R) E3-1235L v5','Skylake'),
			('Intel(R) Xeon(R) E3-1230 v5','Skylake'),
			('Intel(R) Xeon(R) E3-1225 v5','Skylake'),
			('Intel(R) Xeon(R) E3-1220 v5','Skylake'),
			('Intel(R) Xeon(R) W-2123','Skylake'),
			('Intel(R) Xeon(R) W-2125','Skylake'),
			('Intel(R) Xeon(R) W-2133','Skylake'),
			('Intel(R) Xeon(R) W-2135','Skylake'),
			('Intel(R) Xeon(R) W-2145','Skylake'),
			('Intel(R) Xeon(R) W-2155','Skylake'),
			('Intel(R) Xeon(TM) W-2175','Skylake'),
			('Intel(R) Xeon(R) W-2195','Skylake'),
			('Intel(R) Z170 Chipset','Skylake'),
			('Intel(R) Q170 Chipset','Skylake'),
			('Intel(R) H170 Chipset','Skylake'),
			('Intel(R) Q150 Chipset','Skylake'),
			('Intel(R) B150 Chipset','Skylake'),
			('Intel(R) H110 Chipset','Skylake'),
			('Mobile Intel(R) HM175 Chipset','Skylake'),
			('Mobile Intel(R) QM175 Chipset','Skylake'),
			('Mobile Intel(R) HM170 Chipset','Skylake'),
			('Mobile Intel(R) QM170 Chipset','Skylake'),
			('Mobile Intel(R) CM238 Chipset','Skylake'),
			('Mobile Intel(R) CM236 Chipset','Skylake'),
			('Intel(R) C236 Chipset','Skylake'),
			('Intel(R) C232 Chipset','Skylake'),
			('Intel(R) Core(TM) i7-2960XM Extreme Edition','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2920XM Extreme Edition','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2860QM','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2820QM','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2760QM','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2720QM','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2715QE','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2710QE','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2700K','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2677M','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2670QM','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2675QM','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2657M','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2655LE','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2649M','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2640M','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2637M','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2635QM','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2630QM','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2629M','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2620M','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2617M','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2610UE','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2600S','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2600K','Sandy Bridge'),
			('Intel(R) Core(TM) i7-2600','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2557M','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2550K','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2540M','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2537M','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2520M','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2515E','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2510E','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2500T','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2500S','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2500K','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2500','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2467M','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2450P','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2450M','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2435M','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2430M','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2410M','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2405S','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2400S','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2400','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2390T','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2380P','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2320','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2310','Sandy Bridge'),
			('Intel(R) Core(TM) i5-2300','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2377M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2375M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2370M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2367M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2365M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2357M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2350M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2348M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2340UE','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2330M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2330E','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2328M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2312M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2310M','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2310E','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2130','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2125','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2120T','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2120','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2105','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2102','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2100T','Sandy Bridge'),
			('Intel(R) Core(TM) i3-2100','Sandy Bridge'),
			('Intel(R) Pentium(R) 997','Sandy Bridge'),
			('Intel(R) Pentium(R) 987','Sandy Bridge'),
			('Intel(R) Pentium(R) 977','Sandy Bridge'),
			('Intel(R) Pentium(R) G645T','Sandy Bridge'),
			('Intel(R) Pentium(R) B980','Sandy Bridge'),
			('Intel(R) Pentium(R) 967','Sandy Bridge'),
			('Intel(R) Pentium(R) B970','Sandy Bridge'),
			('Intel(R) Pentium(R) G645','Sandy Bridge'),
			('Intel(R) Pentium(R) 957','Sandy Bridge'),
			('Intel(R) Pentium(R) B960','Sandy Bridge'),
			('Intel(R) Pentium(R) G640T','Sandy Bridge'),
			('Intel(R) Pentium(R) G640','Sandy Bridge'),
			('Intel(R) Pentium(R) G870','Sandy Bridge'),
			('Intel(R) Pentium(R) B950','Sandy Bridge'),
			('Intel(R) Pentium(R) G632','Sandy Bridge'),
			('Intel(R) Pentium(R) B940','Sandy Bridge'),
			('Intel(R) Pentium(R) G860T','Sandy Bridge'),
			('Intel(R) Pentium(R) G630T','Sandy Bridge'),
			('Intel(R) Pentium(R) G860','Sandy Bridge'),
			('Intel(R) Pentium(R) G630','Sandy Bridge'),
			('Intel(R) Pentium(R) G850','Sandy Bridge'),
			('Intel(R) Pentium(R) G622','Sandy Bridge'),
			('Intel(R) Pentium(R) G840','Sandy Bridge'),
			('Intel(R) Pentium(R) G620T','Sandy Bridge'),
			('Intel(R) Pentium(R) G620','Sandy Bridge'),
			('Intel(R) Celeron(R) 797','Sandy Bridge'),
			('Intel(R) Celeron(R) 787','Sandy Bridge'),
			('Intel(R) Celeron(R) G470','Sandy Bridge'),
			('Intel(R) Celeron(R) 887','Sandy Bridge'),
			('Intel(R) Celeron(R) G465','Sandy Bridge'),
			('Intel(R) Celeron(R) G460','Sandy Bridge'),
			('Intel(R) Celeron(R) B720','Sandy Bridge'),
			('Intel(R) Celeron(R) 877','Sandy Bridge'),
			('Intel(R) Celeron(R) G440','Sandy Bridge'),
			('Intel(R) Celeron(R) B710','Sandy Bridge'),
			('Intel(R) Celeron(R) B840','Sandy Bridge'),
			('Intel(R) Celeron(R) 867','Sandy Bridge'),
			('Intel(R) Celeron(R) G555','Sandy Bridge'),
			('Intel(R) Celeron(R) G550T','Sandy Bridge'),
			('Intel(R) Celeron(R) 857','Sandy Bridge'),
			('Intel(R) Celeron(R) B830','Sandy Bridge'),
			('Intel(R) Celeron(R) G550','Sandy Bridge'),
			('Intel(R) Celeron(R) 847E','Sandy Bridge'),
			('Intel(R) Celeron(R) B820','Sandy Bridge'),
			('Intel(R) Celeron(R) G540T','Sandy Bridge'),
			('Intel(R) Celeron(R) 847','Sandy Bridge'),
			('Intel(R) Celeron(R) B815','Sandy Bridge'),
			('Intel(R) Celeron(R) G540','Sandy Bridge'),
			('Intel(R) Celeron(R) B810E','Sandy Bridge'),
			('Intel(R) Celeron(R) 827E','Sandy Bridge'),
			('Intel(R) Celeron(R) G530T','Sandy Bridge'),
			('Intel(R) Celeron(R) B810','Sandy Bridge'),
			('Intel(R) Celeron(R) 807UE','Sandy Bridge'),
			('Intel(R) Celeron(R) G530','Sandy Bridge'),
			('Intel(R) Celeron(R) B800','Sandy Bridge'),
			('Intel(R) Celeron(R) 807','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1290','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1280','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1275','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1270','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1260L','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1245','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1240','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1235','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1230','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1225','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1220L','Sandy Bridge'),
			('Intel(R) Xeon(R) E3-1220','Sandy Bridge'),
			('Intel(R) Core(TM) i7-3940XM Extreme Edition','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3920XM Extreme Edition','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3840QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3820QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3770T','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3770S','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3770K','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3770','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3740QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3720QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3689Y','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3687U','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3667U','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3635QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3632QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3632QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3630QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3615QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3615QE','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3612QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3612QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3612QE','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3610QM','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3610QE','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3555LE','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3540M','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3537U','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3520M','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3517UE','Ivy Bridge'),
			('Intel(R) Core(TM) i7-3517U','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3610ME','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3570S','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3570T','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3570K','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3570','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3550S','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3550','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3475S','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3470T','Ivy Bridge');

GO

INSERT INTO #Processors (ProcName,CodeName)
VALUES 
			('Intel(R) Core(TM) i5-3470S','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3470','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3450S','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3450','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3439Y','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3437U','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3427U','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3380M','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3360M','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3350P','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3340S','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3340M','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3340','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3339Y','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3337U','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3330S','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3330','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3320M','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3210M','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3317U','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3230M','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3230M','Ivy Bridge'),
			('Intel(R) Core(TM) i5-3210M','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3250T','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3250','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3245','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3240T','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3240','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3229Y','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3227U','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3225','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3220T','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3220','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3217UE','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3217U','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3210','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3130M','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3120ME','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3120M','Ivy Bridge'),
			('Intel(R) Core(TM) i3-3110M','Ivy Bridge'),
			('Intel(R) Pentium(R) G2140','Ivy Bridge'),
			('Intel(R) Pentium(R) G2130','Ivy Bridge'),
			('Intel(R) Pentium(R) G2120T','Ivy Bridge'),
			('Intel(R) Pentium(R) G2120','Ivy Bridge'),
			('Intel(R) Pentium(R) G2100T','Ivy Bridge'),
			('Intel(R) Pentium(R) G2030T','Ivy Bridge'),
			('Intel(R) Pentium(R) G2030','Ivy Bridge'),
			('Intel(R) Pentium(R) G2020T','Ivy Bridge'),
			('Intel(R) Pentium(R) G2020','Ivy Bridge'),
			('Intel(R) Pentium(R) G2010','Ivy Bridge'),
			('Intel(R) Pentium(R) 2129Y','Ivy Bridge'),
			('Intel(R) Pentium(R) 2127U','Ivy Bridge'),
			('Intel(R) Pentium(R) 2117U','Ivy Bridge'),
			('Intel(R) Pentium(R) 2030M','Ivy Bridge'),
			('Intel(R) Pentium(R) 2020M','Ivy Bridge'),
			('Intel(R) Pentium(R) 1405 v2','Ivy Bridge'),
			('Intel(R) Pentium(R) A1018','Ivy Bridge'),
			('Intel(R) Celeron(R) G1630','Ivy Bridge'),
			('Intel(R) Celeron(R) G1620T','Ivy Bridge'),
			('Intel(R) Celeron(R) G1620','Ivy Bridge'),
			('Intel(R) Celeron(R) G1610T','Ivy Bridge'),
			('Intel(R) Celeron(R) G1610','Ivy Bridge'),
			('Intel(R) Celeron(R) 1047UE','Ivy Bridge'),
			('Intel(R) Celeron(R) 1037U','Ivy Bridge'),
			('Intel(R) Celeron(R) 1020M','Ivy Bridge'),
			('Intel(R) Celeron(R) 1020E','Ivy Bridge'),
			('Intel(R) Celeron(R) 1019Y','Ivy Bridge'),
			('Intel(R) Celeron(R) 1017U','Ivy Bridge'),
			('Intel(R) Celeron(R) 1007U','Ivy Bridge'),
			('Intel(R) Celeron(R) 1005M','Ivy Bridge'),
			('Intel(R) Celeron(R) 1000M','Ivy Bridge'),
			('Intel(R) Celeron(R) 927UE','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-8850 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-8857 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-8870 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-8880 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-8880L v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-8890 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-8891 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-8893 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-4890 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-4880 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-4870 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-4860 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-4850 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-4830 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-4820 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-4809 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-2890 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-2880 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-2870 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E7-2850 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1290 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1280 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1275 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1270 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1265L v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1245 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1240 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1230 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1225 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1220 v2','Ivy Bridge'),
			('Intel(R) Xeon(R) E3-1220L v2','Ivy Bridge'),
			('Intel(R) Xeon(R) X5690','Westmere'),
			('Intel(R) Xeon(R) X5687','Westmere'),
			('Intel(R) Xeon(R) X5680','Westmere'),
			('Intel(R) Xeon(R) W3680','Westmere'),
			('Intel(R) Xeon(R) X5677','Westmere'),
			('Intel(R) Xeon(R) W3670','Westmere'),
			('Intel(R) Xeon(R) X5675','Westmere'),
			('Intel(R) Xeon(R) X5672','Westmere'),
			('Intel(R) Xeon(R) X5670','Westmere'),
			('Intel(R) Xeon(R) X5667','Westmere'),
			('Intel(R) Xeon(R) X5660','Westmere'),
			('Intel(R) Xeon(R) X5650','Westmere'),
			('Intel(R) Xeon(R) X5647','Westmere'),
			('Intel(R) Xeon(R) L5640','Westmere'),
			('Intel(R) Xeon(R) L5638','Westmere'),
			('Intel(R) Xeon(R) L5630','Westmere'),
			('Intel(R) Xeon(R) L5618','Westmere'),
			('Intel(R) Xeon(R) L5609','Westmere'),
			('Intel(R) Xeon(R) E5649','Westmere'),
			('Intel(R) Xeon(R) E5645','Westmere'),
			('Intel(R) Xeon(R) E5640','Westmere'),
			('Intel(R) Xeon(R) E5630','Westmere'),
			('Intel(R) Xeon(R) E5620','Westmere'),
			('Intel(R) Xeon(R) E5607','Westmere'),
			('Intel(R) Xeon(R) E5606','Westmere'),
			('Intel(R) Xeon(R) E5603','Westmere'),
			('Intel(R) Core(TM) i7-4940MX Extreme Edition','Haswell'),
			('Intel(R) Core(TM) i7-4930MX Extreme Edition','Haswell'),
			('Intel(R) Core(TM) i7-4900MQ','Haswell'),
			('Intel(R) Core(TM) i7-4910MQ','Haswell'),
			('Intel(R) Core(TM) i7-4800MQ','Haswell'),
			('Intel(R) Core(TM) i7-4810MQ','Haswell'),
			('Intel(R) Core(TM) i7-4700EC','Haswell'),
			('Intel(R) Core(TM) i7-4700EQ','Haswell'),
			('Intel(R) Core(TM) i7-4700HQ','Haswell'),
			('Intel(R) Core(TM) i7-4700MQ','Haswell'),
			('Intel(R) Core(TM) i7-4702EC','Haswell'),
			('Intel(R) Core(TM) i7-4702HQ','Haswell'),
			('Intel(R) Core(TM) i7-4702MQ','Haswell'),
			('Intel(R) Core(TM) i7-4710HQ','Haswell'),
			('Intel(R) Core(TM) i7-4710MQ','Haswell'),
			('Intel(R) Core(TM) i7-4712HQ','Haswell'),
			('Intel(R) Core(TM) i7-4712MQ','Haswell'),
			('Intel(R) Core(TM) i7-4720HQ','Haswell'),
			('Intel(R) Core(TM) i7-4722HQ','Haswell'),
			('Intel(R) Core(TM) i7-4770K','Haswell'),
			('Intel(R) Core(TM) i7-4765T','Haswell'),
			('Intel(R) Core(TM) i7-4770','Haswell'),
			('Intel(R) Core(TM) i7-4770S','Haswell'),
			('Intel(R) Core(TM) i7-4770T','Haswell'),
			('Intel(R) Core(TM) i7-4770TE','Haswell'),
			('Intel(R) Core(TM) i7-4771','Haswell'),
			('Intel(R) Core(TM) i7-4785T','Haswell'),
			('Intel(R) Core(TM) i7-4790','Haswell'),
			('Intel(R) Core(TM) i7-4790S','Haswell'),
			('Intel(R) Core(TM) i7-4790T','Haswell'),
			('Intel(R) Core(TM) i7-4600M','Haswell'),
			('Intel(R) Core(TM) i7-4600U','Haswell'),
			('Intel(R) Core(TM) i7-4610M','Haswell'),
			('Intel(R) Core(TM) i7-4610Y','Haswell'),
			('Intel(R) Core(TM) i7-4650U','Haswell'),
			('Intel(R) Core(TM) i7-4500U','Haswell'),
			('Intel(R) Core(TM) i7-4510U','Haswell'),
			('Intel(R) Core(TM) i7-4550U','Haswell'),
			('Intel(R) Core(TM) i7-4558U','Haswell'),
			('Intel(R) Core(TM) i7-4578U','Haswell'),
			('Intel(R) Core(TM) i5-4670','Haswell'),
			('Intel(R) Core(TM) i5-4670K','Haswell'),
			('Intel(R) Core(TM) i5-4670S','Haswell'),
			('Intel(R) Core(TM) i5-4670T','Haswell'),
			('Intel(R) Core(TM) i5-4690','Haswell'),
			('Intel(R) Core(TM) i5-4690S','Haswell'),
			('Intel(R) Core(TM) i5-4690T','Haswell'),
			('Intel(R) Core(TM) i5-4570','Haswell'),
			('Intel(R) Core(TM) i5-4570S','Haswell'),
			('Intel(R) Core(TM) i5-4570T','Haswell'),
			('Intel(R) Core(TM) i5-4570TE','Haswell'),
			('Intel(R) Core(TM) i5-4590','Haswell'),
			('Intel(R) Core(TM) i5-4590S','Haswell'),
			('Intel(R) Core(TM) i5-4590T','Haswell'),
			('Intel(R) Core(TM) i5-4422E','Haswell'),
			('Intel(R) Core(TM) i5-4410E','Haswell'),
			('Intel(R) Core(TM) i5-4402EC','Haswell'),
			('Intel(R) Core(TM) i5-4402E','Haswell'),
			('Intel(R) Core(TM) i5-4400E','Haswell'),
			('Intel(R) Core(TM) i5-4460T','Haswell'),
			('Intel(R) Core(TM) i5-4460S','Haswell'),
			('Intel(R) Core(TM) i5-4460','Haswell'),
			('Intel(R) Core(TM) i5-4440S','Haswell'),
			('Intel(R) Core(TM) i5-4440','Haswell'),
			('Intel(R) Core(TM) i5-4430S','Haswell'),
			('Intel(R) Core(TM) i5-4430','Haswell'),
			('Intel(R) Core(TM) i5-4300M','Haswell'),
			('Intel(R) Core(TM) i5-4300U','Haswell'),
			('Intel(R) Core(TM) i5-4300Y','Haswell'),
			('Intel(R) Core(TM) i5-4302Y','Haswell'),
			('Intel(R) Core(TM) i5-4308U','Haswell'),
			('Intel(R) Core(TM) i5-4310M','Haswell'),
			('Intel(R) Core(TM) i5-4310U','Haswell'),
			('Intel(R) Core(TM) i5-4330M','Haswell'),
			('Intel(R) Core(TM) i5-4340M','Haswell'),
			('Intel(R) Core(TM) i5-4350U','Haswell'),
			('Intel(R) Core(TM) i5-4360U','Haswell'),
			('Intel(R) Core(TM) i5-4200H','Haswell'),
			('Intel(R) Core(TM) i5-4200M','Haswell'),
			('Intel(R) Core(TM) i5-4200U','Haswell'),
			('Intel(R) Core(TM) i5-4200Y','Haswell'),
			('Intel(R) Core(TM) i5-4202Y','Haswell'),
			('Intel(R) Core(TM) i5-4210H','Haswell'),
			('Intel(R) Core(TM) i5-4210M','Haswell'),
			('Intel(R) Core(TM) i5-4210U','Haswell'),
			('Intel(R) Core(TM) i5-4210Y','Haswell'),
			('Intel(R) Core(TM) i5-4220Y','Haswell'),
			('Intel(R) Core(TM) i5-4250U','Haswell'),
			('Intel(R) Core(TM) i5-4258U','Haswell'),
			('Intel(R) Core(TM) i5-4260U','Haswell'),
			('Intel(R) Core(TM) i5-4278U','Haswell'),
			('Intel(R) Core(TM) i5-4288U','Haswell'),
			('Intel(R) Core(TM) i3-4330','Haswell'),
			('Intel(R) Core(TM) i3-4330T','Haswell'),
			('Intel(R) Core(TM) i3-4330TE','Haswell'),
			('Intel(R) Core(TM) i3-4340','Haswell'),
			('Intel(R) Core(TM) i3-4340TE','Haswell'),
			('Intel(R) Core(TM) i3-4350','Haswell'),
			('Intel(R) Core(TM) i3-4350T','Haswell'),
			('Intel(R) Core(TM) i3-4360','Haswell'),
			('Intel(R) Core(TM) i3-4360T','Haswell'),
			('Intel(R) Core(TM) i3-4370','Haswell'),
			('Intel(R) Core(TM) i3-4370T','Haswell'),
			('Intel(R) Core(TM) i3-4100E','Haswell'),
			('Intel(R) Core(TM) i3-4100M','Haswell'),
			('Intel(R) Core(TM) i3-4100U','Haswell'),
			('Intel(R) Core(TM) i3-4102E','Haswell'),
			('Intel(R) Core(TM) i3-4110E','Haswell'),
			('Intel(R) Core(TM) i3-4110M','Haswell'),
			('Intel(R) Core(TM) i3-4112E','Haswell'),
			('Intel(R) Core(TM) i3-4120U','Haswell'),
			('Intel(R) Core(TM) i3-4158U','Haswell'),
			('Intel(R) Core(TM) i3-4170T','Haswell'),
			('Intel(R) Core(TM) i3-4170','Haswell'),
			('Intel(R) Core(TM) i3-4160T','Haswell'),
			('Intel(R) Core(TM) i3-4160','Haswell'),
			('Intel(R) Core(TM) i3-4150T','Haswell'),
			('Intel(R) Core(TM) i3-4150','Haswell'),
			('Intel(R) Core(TM) i3-4130T','Haswell'),
			('Intel(R) Core(TM) i3-4130','Haswell'),
			('Intel(R) Core(TM) i3-4000M','Haswell'),
			('Intel(R) Core(TM) i3-4005U','Haswell'),
			('Intel(R) Core(TM) i3-4010U','Haswell'),
			('Intel(R) Core(TM) i3-4010Y','Haswell'),
			('Intel(R) Core(TM) i3-4012Y','Haswell'),
			('Intel(R) Core(TM) i3-4020Y','Haswell'),
			('Intel(R) Core(TM) i3-4025U','Haswell'),
			('Intel(R) Core(TM) i3-4030U','Haswell'),
			('Intel(R) Core(TM) i3-4030Y','Haswell'),
			('Intel(R) Pentium(R) G3470','Haswell'),
			('Intel(R) Pentium(R) G3460T','Haswell'),
			('Intel(R) Pentium(R) G3460','Haswell'),
			('Intel(R) Pentium(R) G3450T','Haswell'),
			('Intel(R) Pentium(R) G3450','Haswell'),
			('Intel(R) Pentium(R) G3440T','Haswell'),
			('Intel(R) Pentium(R) G3440','Haswell'),
			('Intel(R) Pentium(R) G3430','Haswell'),
			('Intel(R) Pentium(R) G3420T','Haswell'),
			('Intel(R) Pentium(R) G3420','Haswell'),
			('Intel(R) Pentium(R) G3260','Haswell'),
			('Intel(R) Pentium(R) G3258','Haswell'),
			('Intel(R) Pentium(R) G3320TE','Haswell'),
			('Intel(R) Pentium(R) G3260T','Haswell'),
			('Intel(R) Pentium(R) G3250T','Haswell'),
			('Intel(R) Pentium(R) G3250','Haswell'),
			('Intel(R) Pentium(R) G3240T','Haswell'),
			('Intel(R) Pentium(R) G3240','Haswell'),
			('Intel(R) Pentium(R) G3220T','Haswell'),
			('Intel(R) Pentium(R) G3220','Haswell'),
			('Intel(R) Pentium(R) 3550M','Haswell'),
			('Intel(R) Pentium(R) 3556U','Haswell'),
			('Intel(R) Pentium(R) 3558U','Haswell'),
			('Intel(R) Pentium(R) 3560M','Haswell'),
			('Intel(R) Pentium(R) 3560Y','Haswell'),
			('Intel(R) Pentium(R) 3561Y','Haswell'),
			('Intel(R) Celeron(R) G1850','Haswell'),
			('Intel(R) Celeron(R) G1840T','Haswell'),
			('Intel(R) Celeron(R) G1840','Haswell'),
			('Intel(R) Celeron(R) G1830','Haswell'),
			('Intel(R) Celeron(R) G1820TE','Haswell'),
			('Intel(R) Celeron(R) G1820T','Haswell'),
			('Intel(R) Celeron(R) G1820','Haswell'),
			('Intel(R) Celeron(R) 2981U','Haswell'),
			('Intel(R) Celeron(R) 2980U','Haswell'),
			('Intel(R) Celeron(R) 2970M','Haswell'),
			('Intel(R) Celeron(R) 2961Y','Haswell'),
			('Intel(R) Celeron(R) 2957U','Haswell'),
			('Intel(R) Celeron(R) 2955U','Haswell'),
			('Intel(R) Celeron(R) 2950M','Haswell'),
			('Intel(R) Celeron(R) 2002E','Haswell'),
			('Intel(R) Celeron(R) 2000E','Haswell'),
			('Intel(R) Xeon(R) E7-8893 v3','Haswell'),
			('Intel(R) Xeon(R) E7-8891 v3','Haswell'),
			('Intel(R) Xeon(R) E7-8890 v3','Haswell'),
			('Intel(R) Xeon(R) E7-8880L v3','Haswell'),
			('Intel(R) Xeon(R) E7-8880 v3','Haswell'),
			('Intel(R) Xeon(R) E7-8870 v3','Haswell'),
			('Intel(R) Xeon(R) E7-8867 v3','Haswell'),
			('Intel(R) Xeon(R) E7-8860 v3','Haswell'),
			('Intel(R) Xeon(R) E7-4850 v3','Haswell'),
			('Intel(R) Xeon(R) E7-4830 v3','Haswell'),
			('Intel(R) Xeon(R) E7-4820 v3','Haswell'),
			('Intel(R) Xeon(R) E7-4809 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2699 v3','Haswell'),
			('Intel(R) Xeon(R) E5-1428L v3','Haswell'),
			('Intel(R) Xeon(R) E5-2438L v3','Haswell'),
			('Intel(R) Xeon(R) E5-4669 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2428L v3','Haswell'),
			('Intel(R) Xeon(R) E5-4667 v3','Haswell'),
			('Intel(R) Xeon(R) E5-1620 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2418L v3','Haswell'),
			('Intel(R) Xeon(R) E5-4660 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2698 v3','Haswell'),
			('Intel(R) Xeon(R) E5-1630 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2408L v3','Haswell'),
			('Intel(R) Xeon(R) E5-4655 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2697 v3','Haswell'),
			('Intel(R) Xeon(R) E5-1650 v3','Haswell'),
			('Intel(R) Xeon(R) E5-4650 v3','Haswell'),
			('Intel(R) Xeon(R) E5-1660 v3','Haswell'),
			('Intel(R) Xeon(R) E5-4648 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2695 v3','Haswell'),
			('Intel(R) Xeon(R) E5-1680 v3','Haswell'),
			('Intel(R) Xeon(R) E5-4640 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2690 v3','Haswell'),
			('Intel(R) Xeon(R) E5-4627 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2687W v3','Haswell'),
			('Intel(R) Xeon(R) E5-4620 v3','Haswell'),
			('Intel(R) Xeon(R) E5-4610 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2683 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2680 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2670 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2667 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2660 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2658A v3','Haswell'),
			('Intel(R) Xeon(R) E5-2658 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2650L v3','Haswell'),
			('Intel(R) Xeon(R) E5-2650 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2648L v3','Haswell'),
			('Intel(R) Xeon(R) E5-2643 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2640 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2637 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2630L v3','Haswell'),
			('Intel(R) Xeon(R) E5-2630 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2628L v3','Haswell'),
			('Intel(R) Xeon(R) E5-2623 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2620 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2618L v3','Haswell'),
			('Intel(R) Xeon(R) E5-2609 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2608L v3','Haswell'),
			('Intel(R) Xeon(R) E5-2603 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1286L v3','Haswell'),
			('Intel(R) Xeon(R) E3-1286 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1285L v3','Haswell'),
			('Intel(R) Xeon(R) E3-1285 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1281 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1280 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1276 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1275L v3','Haswell'),
			('Intel(R) Xeon(R) E3-1270 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1268L v3','Haswell'),
			('Intel(R) Xeon(R) E3-1271 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1275 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1265L v3','Haswell'),
			('Intel(R) Xeon(R) E3-1246 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1245 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1241 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1240L v3','Haswell'),
			('Intel(R) Xeon(R) E3-1240 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1231 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1230L v3','Haswell'),
			('Intel(R) Xeon(R) E3-1230 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1226 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1225 v3','Haswell'),
			('Intel(R) Xeon(R) E3-1220L v3','Haswell'),
			('Intel(R) Xeon(R) E3-1220 v3','Haswell'),
			('Intel(R) Core(TM) i7-7740X X-series','Kaby Lake'),
			('Intel(R) Core(TM) i5-7640X X-series','Kaby Lake'),
			('Intel(R) Core(TM) i7-7920HQ','Kaby Lake'),
			('Intel(R) Core(TM) i7-7820HQ','Kaby Lake'),
			('Intel(R) Core(TM) i7-7820HK','Kaby Lake'),
			('Intel(R) Core(TM) i7-7820EQ','Kaby Lake'),
			('Intel(R) Core(TM) i7-7700HQ','Kaby Lake'),
			('Intel(R) Core(TM) i7-7700','Kaby Lake'),
			('Intel(R) Core(TM) i7-7700K','Kaby Lake'),
			('Intel(R) Core(TM) i7-7700T','Kaby Lake'),
			('Intel(R) Core(TM) i7-7660U','Kaby Lake'),
			('Intel(R) Core(TM) i7-7600U','Kaby Lake'),
			('Intel(R) Core(TM) i7-7567U','Kaby Lake'),
			('Intel(R) Core(TM) i7-7560U','Kaby Lake'),
			('Intel(R) Core(TM) i7-7500U','Kaby Lake'),
			('Intel(R) Core(TM) i7-7Y75','Kaby Lake'),
			('Intel(R) Core(TM) i5-7600K','Kaby Lake'),
			('Intel(R) Core(TM) i5-7600T','Kaby Lake'),
			('Intel(R) Core(TM) i5-7600','Kaby Lake'),
			('Intel(R) Core(TM) i5-7500','Kaby Lake'),
			('Intel(R) Core(TM) i5-7500T','Kaby Lake'),
			('Intel(R) Core(TM) i5-7442EQ','Kaby Lake'),
			('Intel(R) Core(TM) i5-7440HQ','Kaby Lake'),
			('Intel(R) Core(TM) i5-7440EQ','Kaby Lake'),
			('Intel(R) Core(TM) i5-7400T','Kaby Lake'),
			('Intel(R) Core(TM) i5-7400','Kaby Lake'),
			('Intel(R) Core(TM) i5-7360U','Kaby Lake'),
			('Intel(R) Core(TM) i5-7300U','Kaby Lake'),
			('Intel(R) Core(TM) i5-7300HQ','Kaby Lake'),
			('Intel(R) Core(TM) i5-7287U','Kaby Lake'),
			('Intel(R) Core(TM) i5-7267U','Kaby Lake'),
			('Intel(R) Core(TM) i5-7260U','Kaby Lake'),
			('Intel(R) Core(TM) i5-7200U','Kaby Lake'),
			('Intel(R) Core(TM) i5-7Y54','Kaby Lake'),
			('Intel(R) Core(TM) i5-7Y57','Kaby Lake'),
			('Intel(R) Core(TM) i3-7350K','Kaby Lake'),
			('Intel(R) Core(TM) i3-7320','Kaby Lake'),
			('Intel(R) Core(TM) i3-7300','Kaby Lake'),
			('Intel(R) Core(TM) i3-7300T','Kaby Lake'),
			('Intel(R) Core(TM) i3-7130U','Kaby Lake'),
			('Intel(R) Core(TM) i3-7102E','Kaby Lake'),
			('Intel(R) Core(TM) i3-7101E','Kaby Lake'),
			('Intel(R) Core(TM) i3-7101TE','Kaby Lake'),
			('Intel(R) Core(TM) i3-7100T','Kaby Lake'),
			('Intel(R) Core(TM) i3-7100E','Kaby Lake'),
			('Intel(R) Core(TM) i3-7100','Kaby Lake'),
			('Intel(R) Core(TM) i3-7167U','Kaby Lake'),
			('Intel(R) Core(TM) i3-7100U','Kaby Lake'),
			('Intel(R) Core(TM) i3-7100H','Kaby Lake'),
			('Intel(R) Core(TM) m3-7Y32','Kaby Lake'),
			('Intel(R) Core(TM) m3-7Y30','Kaby Lake'),
			('Intel(R) Pentium(R) G4620','Kaby Lake'),
			('Intel(R) Pentium(R) G4600T','Kaby Lake'),
			('Intel(R) Pentium(R) G4600','Kaby Lake'),
			('Intel(R) Pentium(R) G4560T','Kaby Lake'),
			('Intel(R) Pentium(R) G4560','Kaby Lake'),
			('Intel(R) Pentium(R) 4415U','Kaby Lake'),
			('Intel(R) Pentium(R) 4415Y','Kaby Lake'),
			('Intel(R) Pentium(R) 4410Y','Kaby Lake'),
			('Intel(R) Celeron(R) G3950','Kaby Lake'),
			('Intel(R) Celeron(R) G3930TE','Kaby Lake'),
			('Intel(R) Celeron(R) G3930T','Kaby Lake'),
			('Intel(R) Celeron(R) G3930E','Kaby Lake'),
			('Intel(R) Celeron(R) G3930','Kaby Lake'),
			('Intel(R) Celeron(R) 3965U','Kaby Lake'),
			('Intel(R) Celeron(R) 3965Y','Kaby Lake'),
			('Intel(R) Celeron(R) 3865U','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1535M v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1505M v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1505L v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1501L v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1501M v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1285 v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1280 v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1275 v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1270 v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1245 v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1240 v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1230 v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1225 v6','Kaby Lake'),
			('Intel(R) Xeon(R) E3-1220 v6','Kaby Lake'),
			('Intel(R) X299 Chipset','Kaby Lake'),
			('Intel(R) Z270 Chipset','Kaby Lake'),
			('Intel(R) Q270 Chipset','Kaby Lake'),
			('Intel(R) H270 Chipset','Kaby Lake'),
			('Intel(R) Q250 Chipset','Kaby Lake'),
			('Intel(R) B250 Chipset','Kaby Lake'),
			('Intel(R) C422 Chipset','Kaby Lake'),
			('Intel(R) Core(TM) i7-8700K','Coffee Lake'),
			('Intel(R) Core(TM) i7-8700','Coffee Lake'),
			('Intel(R) Core(TM) i5-8600K','Coffee Lake'),
			('Intel(R) Core(TM) i5-8400','Coffee Lake'),
			('Intel(R) Core(TM) i3-8350K','Coffee Lake'),
			('Intel(R) Core(TM) i3-8100','Coffee Lake'),
			('Intel(R) Z370 Chipset','Coffee Lake'),
			('Intel(R) Pentium(R) Silver J5005','Gemini Lake'),
			('Intel(R) Pentium(R) Silver N5000','Gemini Lake'),
			('Intel(R) Celeron(R) J4105','Gemini Lake'),
			('Intel(R) Celeron(R) J4005','Gemini Lake'),
			('Intel(R) Celeron(R) N4100','Gemini Lake'),
			('Intel(R) Celeron(R) N4000','Gemini Lake'),
			('Intel(R) Pentium(R) J4205','Apollo Lake'),
			('Intel(R) Pentium(R) N4200','Apollo Lake'),
			('Intel(R) Celeron(R) J3455','Apollo Lake'),
			('Intel(R) Celeron(R) J3355','Apollo Lake'),
			('Intel(R) Celeron(R) N3350','Apollo Lake'),
			('Intel(R) Celeron(R) N3450','Apollo Lake'),
			('Intel Atom(R) x7-E3950','Apollo Lake'),
			('Intel Atom(R) x5-E3940','Apollo Lake'),
			('Intel Atom(R) x5-E3930','Apollo Lake'),
			('Intel(R) Pentium(R) J2900','Bay Trail'),
			('Intel(R) Pentium(R) J2850','Bay Trail'),
			('Intel(R) Pentium(R) N3540','Bay Trail'),
			('Intel(R) Pentium(R) N3530','Bay Trail'),
			('Intel(R) Pentium(R) N3520','Bay Trail'),
			('Intel(R) Pentium(R) N3510','Bay Trail'),
			('Intel(R) Pentium(R) A1020','Bay Trail'),
			('Intel(R) Celeron(R) J1900','Bay Trail'),
			('Intel(R) Celeron(R) J1850','Bay Trail'),
			('Intel(R) Celeron(R) J1800','Bay Trail');

Go

INSERT INTO #Processors (ProcName,CodeName)
VALUES 
			('Intel(R) Celeron(R) J1750','Bay Trail'),
			('Intel(R) Celeron(R) N2940','Bay Trail'),
			('Intel(R) Celeron(R) N2930','Bay Trail'),
			('Intel(R) Celeron(R) N2920','Bay Trail'),
			('Intel(R) Celeron(R) N2910','Bay Trail'),
			('Intel(R) Celeron(R) N2840','Bay Trail'),
			('Intel(R) Celeron(R) N2830','Bay Trail'),
			('Intel(R) Celeron(R) N2820','Bay Trail'),
			('Intel(R) Celeron(R) N2815','Bay Trail'),
			('Intel(R) Celeron(R) N2810','Bay Trail'),
			('Intel(R) Celeron(R) N2808','Bay Trail'),
			('Intel(R) Celeron(R) N2807','Bay Trail'),
			('Intel(R) Celeron(R) N2806','Bay Trail'),
			('Intel(R) Celeron(R) N2805','Bay Trail'),
			('Intel Atom(R) E3845','Bay Trail'),
			('Intel Atom(R) E3827','Bay Trail'),
			('Intel Atom(R) E3826','Bay Trail'),
			('Intel Atom(R) E3825','Bay Trail'),
			('Intel Atom(R) E3815','Bay Trail'),
			('Intel Atom(R) E3805','Bay Trail'),
			('Intel Atom(R) Z3795','Bay Trail'),
			('Intel Atom(R) Z3785','Bay Trail'),
			('Intel Atom(R) Z3775D','Bay Trail'),
			('Intel Atom(R) Z3775','Bay Trail'),
			('Intel Atom(R) Z3770D','Bay Trail'),
			('Intel Atom(R) Z3770','Bay Trail'),
			('Intel Atom(R) Z3745D','Bay Trail'),
			('Intel Atom(R) Z3745','Bay Trail'),
			('Intel Atom(R) Z3740D','Bay Trail'),
			('Intel Atom(R) Z3740','Bay Trail'),
			('Intel Atom(R) Z3736G','Bay Trail'),
			('Intel Atom(R) Z3736F','Bay Trail'),
			('Intel Atom(R) Z3735G','Bay Trail'),
			('Intel Atom(R) Z3735F','Bay Trail'),
			('Intel Atom(R) Z3735E','Bay Trail'),
			('Intel Atom(R) Z3735D','Bay Trail'),
			('Intel Atom(R) x7-Z8750','Cherry Trail'),
			('Intel Atom(R) x7-Z8700','Cherry Trail'),
			('Intel Atom(R) x5-Z8550','Cherry Trail'),
			('Intel Atom(R) x5-Z8500','Cherry Trail'),
			('Intel Atom(R) x5-Z8350','Cherry Trail'),
			('Intel Atom(R) x5-Z8330','Cherry Trail'),
			('Intel Atom(R) x5-Z8300','Cherry Trail'),
			('Intel(R) Xeon(R) X5570','Nehalem EP'),
			('Intel(R) Xeon(R) X5560','Nehalem EP'),
			('Intel(R) Xeon(R) X5550','Nehalem EP'),
			('Intel(R) Xeon(R) W5590','Nehalem EP'),
			('Intel(R) Xeon(R) W5580','Nehalem EP'),
			('Intel(R) Xeon(R) L5530','Nehalem EP'),
			('Intel(R) Xeon(R) L5520','Nehalem EP'),
			('Intel(R) Xeon(R) L5518','Nehalem EP'),
			('Intel(R) Xeon(R) L5508','Nehalem EP'),
			('Intel(R) Xeon(R) L5506','Nehalem EP'),
			('Intel(R) Xeon(R) E5540','Nehalem EP'),
			('Intel(R) Xeon(R) E5530','Nehalem EP'),
			('Intel(R) Xeon(R) E5520','Nehalem EP'),
			('Intel(R) Xeon(R) E5507','Nehalem EP'),
			('Intel(R) Xeon(R) E5506','Nehalem EP'),
			('Intel(R) Xeon(R) E5504','Nehalem EP'),
			('Intel(R) Xeon(R) E5503','Nehalem EP'),
			('Intel(R) Xeon(R) E5502','Nehalem EP'),
			('Intel(R) Core(TM) i7-610E','Arrandale'),
			('Intel(R) Core(TM) i5-480M','Arrandale'),
			('Intel(R) Core(TM) i3-390M','Arrandale'),
			('Intel(R) Core(TM) i7-680UM','Arrandale'),
			('Intel(R) Core(TM) i7-660UM','Arrandale'),
			('Intel(R) Core(TM) i7-660UE','Arrandale'),
			('Intel(R) Core(TM) i7-660LM','Arrandale'),
			('Intel(R) Core(TM) i7-640UM','Arrandale'),
			('Intel(R) Core(TM) i7-640M','Arrandale'),
			('Intel(R) Core(TM) i7-640LM','Arrandale'),
			('Intel(R) Core(TM) i7-620UM','Arrandale'),
			('Intel(R) Core(TM) i7-620UE','Arrandale'),
			('Intel(R) Core(TM) i7-620M','Arrandale'),
			('Intel(R) Core(TM) i7-620LM','Arrandale'),
			('Intel(R) Core(TM) i7-620LE','Arrandale'),
			('Intel(R) Core(TM) i5-580M','Arrandale'),
			('Intel(R) Core(TM) i5-560UM','Arrandale'),
			('Intel(R) Core(TM) i5-560M','Arrandale'),
			('Intel(R) Core(TM) i5-540UM','Arrandale'),
			('Intel(R) Core(TM) i5-540M','Arrandale'),
			('Intel(R) Core(TM) i5-520UM','Arrandale'),
			('Intel(R) Core(TM) i5-520M','Arrandale'),
			('Intel(R) Core(TM) i5-520E','Arrandale'),
			('Intel(R) Core(TM) i5-470UM','Arrandale'),
			('Intel(R) Core(TM) i5-460M','Arrandale'),
			('Intel(R) Core(TM) i5-450M','Arrandale'),
			('Intel(R) Core(TM) i5-430UM','Arrandale'),
			('Intel(R) Core(TM) i5-430M','Arrandale'),
			('Intel(R) Core(TM) i3-380UM','Arrandale'),
			('Intel(R) Core(TM) i3-380M','Arrandale'),
			('Intel(R) Core(TM) i3-370M','Arrandale'),
			('Intel(R) Core(TM) i3-350M','Arrandale'),
			('Intel(R) Core(TM) i3-330UM','Arrandale'),
			('Intel(R) Core(TM) i3-330M','Arrandale'),
			('Intel(R) Core(TM) i3-330E','Arrandale'),
			('Intel(R) Pentium(R) P6000','Arrandale'),
			('Intel(R) Pentium(R) U5400','Arrandale'),
			('Intel(R) Pentium(R) U5600','Arrandale'),
			('Intel(R) Pentium(R) P6100','Arrandale'),
			('Intel(R) Pentium(R) P6200','Arrandale'),
			('Intel(R) Pentium(R) P6300','Arrandale'),
			('Intel(R) Celeron(R) P4500','Arrandale'),
			('Intel(R) Celeron(R) U3400','Arrandale'),
			('Intel(R) Celeron(R) P4505','Arrandale'),
			('Intel(R) Celeron(R) U3405','Arrandale'),
			('Intel(R) Celeron(R) U3600','Arrandale'),
			('Intel(R) Celeron(R) P4600','Arrandale'),
			('Intel(R) Core(TM) i5-680','Clarkdale'),
			('Intel(R) Core(TM) i3-560','Clarkdale'),
			('Intel(R) Core(TM) i5-670','Clarkdale'),
			('Intel(R) Core(TM) i5-661','Clarkdale'),
			('Intel(R) Core(TM) i5-660','Clarkdale'),
			('Intel(R) Core(TM) i5-655K','Clarkdale'),
			('Intel(R) Core(TM) i5-650','Clarkdale'),
			('Intel(R) Core(TM) i3-550','Clarkdale'),
			('Intel(R) Core(TM) i3-540','Clarkdale'),
			('Intel(R) Core(TM) i3-530','Clarkdale'),
			('Intel(R) Pentium(R) G6951','Clarkdale'),
			('Intel(R) Pentium(R) G6950','Clarkdale'),
			('Intel(R) Pentium(R) G6960','Clarkdale'),
			('Intel(R) Xeon(R) L3406','Clarkdale'),
			('Intel(R) Xeon(R) X5492','Harpertown'),
			('Intel(R) Xeon(R) X5482','Harpertown'),
			('Intel(R) Xeon(R) X5472','Harpertown'),
			('Intel(R) Xeon(R) X5470','Harpertown'),
			('Intel(R) Xeon(R) X5460','Harpertown'),
			('Intel(R) Xeon(R) X5450','Harpertown'),
			('Intel(R) Xeon(R) L5430','Harpertown'),
			('Intel(R) Xeon(R) L5420','Harpertown'),
			('Intel(R) Xeon(R) L5410','Harpertown'),
			('Intel(R) Xeon(R) L5408','Harpertown'),
			('Intel(R) Xeon(R) E5472','Harpertown'),
			('Intel(R) Xeon(R) E5462','Harpertown'),
			('Intel(R) Xeon(R) E5450','Harpertown'),
			('Intel(R) Xeon(R) E5440','Harpertown'),
			('Intel(R) Xeon(R) E5430','Harpertown'),
			('Intel(R) Xeon(R) E5420','Harpertown'),
			('Intel(R) Xeon(R) E5410','Harpertown'),
			('Intel(R) Xeon(R) E5405','Harpertown'),
			('Intel(R) Core(TM)2 Duo E8600','Wolfdale'),
			('Intel(R) Core(TM)2 Duo E8500','Wolfdale'),
			('Intel(R) Core(TM)2 Duo E8400','Wolfdale'),
			('Intel(R) Core(TM)2 Duo E8300','Wolfdale'),
			('Intel(R) Core(TM)2 Duo E8200','Wolfdale'),
			('Intel(R) Core(TM)2 Duo E8190','Wolfdale'),
			('Intel(R) Core(TM)2 Duo E7600','Wolfdale'),
			('Intel(R) Core(TM)2 Duo E7500','Wolfdale'),
			('Intel(R) Core(TM)2 Duo E7400','Wolfdale'),
			('Intel(R) Core(TM)2 Duo E7300','Wolfdale'),
			('Intel(R) Core(TM)2 Duo E7200','Wolfdale'),
			('Intel(R) Pentium(R) E5200','Wolfdale'),
			('Intel(R) Pentium(R) E6300','Wolfdale'),
			('Intel(R) Pentium(R) E5300','Wolfdale'),
			('Intel(R) Pentium(R) E5400','Wolfdale'),
			('Intel(R) Pentium(R) E6500','Wolfdale'),
			('Intel(R) Pentium(R) E6500K','Wolfdale'),
			('Intel(R) Pentium(R) E5500','Wolfdale'),
			('Intel(R) Pentium(R) E6600','Wolfdale'),
			('Intel(R) Pentium(R) E5700','Wolfdale'),
			('Intel(R) Pentium(R) E5800','Wolfdale'),
			('Intel(R) Pentium(R) E6700','Wolfdale'),
			('Intel(R) Pentium(R) E6800','Wolfdale'),
			('Intel(R) Celeron(R) E3200','Wolfdale'),
			('Intel(R) Celeron(R) E3300','Wolfdale'),
			('Intel(R) Celeron(R) E3400','Wolfdale'),
			('Intel(R) Celeron(R) E3500','Wolfdale'),
			('Intel(R) Xeon(R) L3110','Wolfdale'),
			('Intel(R) Xeon(R) X5272','Wolfdale'),
			('Intel(R) Xeon(R) E3120','Wolfdale'),
			('Intel(R) Xeon(R) L3014','Wolfdale'),
			('Intel(R) Xeon(R) X5270','Wolfdale'),
			('Intel(R) Xeon(R) X5260','Wolfdale'),
			('Intel(R) Xeon(R) E3110','Wolfdale'),
			('Intel(R) Xeon(R) L5240','Wolfdale'),
			('Intel(R) Xeon(R) L5238','Wolfdale'),
			('Intel(R) Xeon(R) L5215','Wolfdale'),
			('Intel(R) Xeon(R) E5240','Wolfdale'),
			('Intel(R) Xeon(R) E5220','Wolfdale'),
			('Intel(R) Xeon(R) E5205','Wolfdale'),
		    ('Intel(R) Xeon(R) E5-4603 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2603 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-1620 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2609 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-4607 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-4610 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-1650 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2618L v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-4620 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-1660 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2620 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2628L v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-4624L v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-4627 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2630 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-4640 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2630L v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-4650 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2637 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2640 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-4657L v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2643 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2648L v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2650 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2650L v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2658 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2660 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2667 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2670 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2680 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2687W v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2690 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2695 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2697 v2','Ivy Bridge EP'),
			('Intel(R) Xeon(R) E5-2603','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-4603','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-4607','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2609','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-4610','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-1620','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-4617','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2620','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-1650','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-4620','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-4640','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-1660','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2630','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-4650','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2630L','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-4650L','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2637','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2640','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2643','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2648L','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2650','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2650L','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2658','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2660','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2665','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2667','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2670','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2680','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2687W','Sandy Bridge EP'),
			('Intel(R) Xeon(R) E5-2690','Sandy Bridge EP');

GO

INSERT INTO #Processors (ProcName,CodeName)
VALUES 
			('Intel(R) Core(TM) i7-4950HQ','Crystal Well'),
			('Intel(R) Core(TM) i7-4960HQ','Crystal Well'),
			('Intel(R) Core(TM) i7-4980HQ','Crystal Well'),
			('Intel(R) Core(TM) i7-4850HQ','Crystal Well'),
			('Intel(R) Core(TM) i7-4860HQ','Crystal Well'),
			('Intel(R) Core(TM) i7-4870HQ','Crystal Well'),
			('Intel(R) Core(TM) i7-4750HQ','Crystal Well'),
			('Intel(R) Core(TM) i7-4760HQ','Crystal Well'),
			('Intel(R) Core(TM) i7-4770HQ','Crystal Well'),
			('Intel(R) Core(TM) i7-4770R','Crystal Well'),
			('Intel(R) Core(TM) i5-4670R','Crystal Well'),
			('Intel(R) Core(TM) i5-4570R','Crystal Well'),
			('Intel(R) Core(TM) i7-4790K','Devils Canyon'),
			('Intel(R) Core(TM) i5-4690K','Devils Canyon'),
			('Intel(R) Core(TM) i5 650 ','Clarkdale'),
			('Intel(R) Xeon(R) E7-8870','Westmere EX'),
			('Intel(R) Xeon(R) E7-8867L','Westmere EX'),
			('Intel(R) Xeon(R) E7-8860','Westmere EX'),
			('Intel(R) Xeon(R) E7-8850','Westmere EX'),
			('Intel(R) Xeon(R) E7-8837','Westmere EX'),
			('Intel(R) Xeon(R) E7-8830','Westmere EX'),
			('Intel(R) Xeon(R) E7-4870','Westmere EX'),
			('Intel(R) Xeon(R) E7-4860','Westmere EX'),
			('Intel(R) Xeon(R) E7-4850','Westmere EX'),
			('Intel(R) Xeon(R) E7-4830','Westmere EX'),
			('Intel(R) Xeon(R) E7-4820','Westmere EX'),
			('Intel(R) Xeon(R) E7-4807','Westmere EX'),
			('Intel(R) Xeon(R) E7-2870','Westmere EX'),
			('Intel(R) Xeon(R) E7-2860','Westmere EX'),
			('Intel(R) Xeon(R) E7-2850','Westmere EX'),
			('Intel(R) Xeon(R) E7-2830','Westmere EX'),
			('Intel(R) Xeon(R) E7-2820','Westmere EX'),
			('Intel(R) Xeon(R) E7-2803','Westmere EX'),
			('Intel(R) Xeon(R) LV 5148','Woodcrest'),
			('Intel(R) Xeon(R) LV 5138','Woodcrest'),
			('Intel(R) Xeon(R) LV 5133','Woodcrest'),
			('Intel(R) Xeon(R) LV 5128','Woodcrest'),
			('Intel(R) Xeon(R) LV 5113','Woodcrest'),
			('Intel(R) Xeon(R) 5160','Woodcrest'),
			('Intel(R) Xeon(R) 5150','Woodcrest'),
			('Intel(R) Xeon(R) 5140','Woodcrest'),
			('Intel(R) Xeon(R) 5130','Woodcrest'),
			('Intel(R) Xeon(R) 5120','Woodcrest'),
			('Intel(R) Xeon(R) 5110','Woodcrest'),
			('Intel(R) Xeon(R) X6550','Nehalem EX'),
			('Intel(R) Xeon(R) X7560','Nehalem EX'),
			('Intel(R) Xeon(R) E6540','Nehalem EX'),
			('Intel(R) Xeon(R) X7550','Nehalem EX'),
			('Intel(R) Xeon(R) E6510','Nehalem EX'),
			('Intel(R) Xeon(R) X7542','Nehalem EX'),
			('Intel(R) Xeon(R) L7555','Nehalem EX'),
			('Intel(R) Xeon(R) L7545','Nehalem EX'),
			('Intel(R) Xeon(R) E7540','Nehalem EX'),
			('Intel(R) Xeon(R) E7530','Nehalem EX'),
			('Intel(R) Xeon(R) E7520','Nehalem EX'),
			('Intel(R) Core(TM) i7-975 Extreme Edition','Bloomfield'),
			('Intel(R) Core(TM) i7-965 Extreme Edition','Bloomfield'),
			('Intel(R) Core(TM) i7-920','Bloomfield'),
			('Intel(R) Core(TM) i7-960','Bloomfield'),
			('Intel(R) Core(TM) i7-950','Bloomfield'),
			('Intel(R) Core(TM) i7-940','Bloomfield'),
			('Intel(R) Core(TM) i7-930','Bloomfield'),
			('Intel(R) Xeon(R) W3580','Bloomfield'),
			('Intel(R) Xeon(R) W3570','Bloomfield'),
			('Intel(R) Xeon(R) W3565','Bloomfield'),
			('Intel(R) Xeon(R) W3550','Bloomfield'),
			('Intel(R) Xeon(R) W3540','Bloomfield'),
			('Intel(R) Xeon(R) W3530','Bloomfield'),
			('Intel(R) Xeon(R) W3520','Bloomfield'),
			('Intel(R) Pentium(R) 1405','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2403','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2407','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-1428L','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2418L','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2420','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2428L','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2430','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2430L','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2440','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2448L','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2450','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2450L','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2470','Sandy Bridge EN'),
			('Intel(R) Xeon(R) E5-2403 v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-1428L v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2407 v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2418L v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2420 v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2428L v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2430 v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2430L v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2440 v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2448L v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2450 v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2450L v2','Ivy Bridge EN'),
			('Intel(R) Xeon(R) E5-2470 v2','Ivy Bridge EN'),
			('Intel(R) Atom(TM) x7-Z8750','Cherry Trail'),
			('Intel(R) Atom(TM) x7-Z8700','Cherry Trail'),
			('Intel(R) Atom(TM) x5-Z8550','Cherry Trail'),
			('Intel(R) Atom(TM) x5-Z8500','Cherry Trail'),
			('Intel(R) Atom(TM) x5-Z8350','Cherry Trail'),
			('Intel(R) Atom(TM) x5-Z8330','Cherry Trail'),
			('Intel(R) Atom(TM) x5-Z8300','Cherry Trail'),
			('Intel(R) Xeon(R) E5-2673 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2673 v4','Broadwell'),
			('Pentium(R) Dual-Core E6500 ','Wolfdale'),
			('Intel(R) Xeon(R) E5-2676 v3','Haswell'),
			('Intel(R) Xeon(R) E5-2686 v4','Broadwell'),
			('Intel(R) Xeon(R) Platinum 8124M','Skylake'),
			('Intel(R) Xeon(R) E5-2666 v3','Haswell'),
			('Intel(R) Xeon(R) Processor','Dempsey'),
			('Intel(R) Xeon(R) Platinum 8175M','Skylake'),
			('Intel(R) Xeon(R) E5-1680 v2','Ivy Bridge EP'),
			('Intel(R) Core(TM) i5 M 560 ','Arrandale'),
			('Intel(R) Core(TM) i5 M 520 ','Arrandale');

GO

Select Distinct 
 sys.Name0 AS SystemName
,replace(replace(replace(replace(replace(replace(replace(replace(LEFT(processor.Name0,CHARINDEX('@',processor.Name0)),' CPU',''),' @',''),' 0',''),'  ',' '),'  ',' '),'  ',' '),'  ',' '),'E7- ','E7-') AS Processor
,OS.Caption0 AS OSName
INTO #PCProcOS
From v_R_System sys
INNER JOIN v_GS_PROCESSOR processor ON processor.ResourceID = sys.ResourceID
INNER JOIN v_GS_OPERATING_SYSTEM OS ON OS.ResourceID = sys.ResourceID
Where LEN(processor.Name0) > 5;

Go

Select   #PCProcOS.SystemName
		,#PCProcOS.OSName
		,#PCProcOS.Processor
		,ISNULL(#Processors.CodeName,'Unknown') AS CodeName
		,ISNULL(#Impact.Impact,'Unknown') AS Impact
		,CASE 
			WHEN #PCProcOS.OSName Like '%Windows 10%' AND #Impact.Impact = 'High' THEN 'Potentially Noticed'
			WHEN #PCProcOS.OSName Like '%Windows 10%' AND #Impact.Impact = 'Low' THEN 'Low'
			WHEN #PCProcOS.OSName Like '%Windows 7%' AND #Impact.Impact = 'High' THEN 'Noticeable'
			WHEN #PCProcOS.OSName Like '%Windows 7%' AND #Impact.Impact = 'Low' THEN 'Potentially Noticed'
			WHEN #PCProcOS.OSName Like '%Windows 8%' AND #Impact.Impact = 'High' THEN 'Noticeable'
			WHEN #PCProcOS.OSName Like '%Windows 8%' AND #Impact.Impact = 'Low' THEN 'Potentially Noticed'
			WHEN #PCProcOS.OSName Like '%Server%' AND #Impact.Impact = 'High' THEN 'Potentially High'
			WHEN #PCProcOS.OSName Like '%Server%' AND #Impact.Impact = 'Low' THEN 'Potentially Low'
		    Else 'Unknown'
		End AS CalculatedImpact
From #PCProcOS
LEFT JOIN #Processors ON #Processors.ProcName = #PCProcOS.Processor
LEFT JOIN #Impact ON #Impact.Codename = #Processors.Codename;

Go

Drop Table #Impact
Drop Table #Processors
Drop Table #PCProcOS

Go
